name: Django CI

on:
  push:
    branches: [ "main", "develop" ]   # corre cuando hagas push a main o develop
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'   # la versión de Python que usas en tu proyecto

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install django

      - name: Migrar base de datos
        run: |
          python manage.py migrate --noinput

      - name: Ejecutar pruebas
        run: |
          python manage.py test
